"""The Real-time Neural MPC benchmark (Table II) with Scaly generating the network's code.

The model is the paper's: a double integrator `x = (s, s_dot)`, `u = s_ddot`, plus an MLP residual
`f_D(x)` read from the PyTorch state dict the baseline trains nothing into (`load_torch_state_dict`, so
this file never imports torch). The layers stay dense matrix-vector loops in the generated C, and
their derivatives go through those loops.

Three uses of it, each against the matching baseline column of `baseline/run_acados.py`:

  dropin   acados with the exact network, its `expl_ode_fun`, `expl_vde_forw` and `expl_vde_adj`
           generated by Scaly instead of CasADi (`install_dropin`); HPIPM, condensing, ERK and the loop
           are acados' own, so this isolates the network's value and sensitivities
  taylor   the RTN-MPC loop with PyTorch's value-and-Jacobian replaced by one Scaly Function over the
           N shooting nodes (`taylor_params`)
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

import scaly as sc
from scaly.codegen import write_module
from scaly.utils import load_torch_state_dict

NX, NU, N = 2, 1, 10


def layers(state_dict: dict[str, np.ndarray]) -> list[tuple[np.ndarray, np.ndarray]]:
  """`(W, b)` per linear layer, input first, in float64, from ml-casadi's MultiLayerPerceptron keys."""
  hidden = sorted({".".join(k.split(".")[:2]) for k in state_dict if k.startswith("hidden_layers.")}, key=lambda k: int(k.split(".")[1]))
  names = ["input_layer", *hidden, "output_layer"]
  return [(np.asarray(state_dict[f"{n}.weight"], np.float64), np.asarray(state_dict[f"{n}.bias"], np.float64)) for n in names]


def load(path: str | Path) -> list[tuple[np.ndarray, np.ndarray]]:
  return layers(load_torch_state_dict(path))


def mlp(params: list[tuple[np.ndarray, np.ndarray]], x: sc.Expr) -> sc.Expr:
  h = x
  for W, b in params[:-1]:
    h = (sc.const(W) @ h + sc.const(b)).tanh()
  W, b = params[-1]
  return sc.const(W) @ h + sc.const(b)


def xdot(params, x: sc.Expr, u: sc.Expr) -> sc.Expr:
  """`[s_dot, u] + f_D(x)`."""
  return sc.concat([x[1:2], u]) + mlp(params, x)


def acados_functions(params, n_p: int = 0) -> dict[str, sc.Function]:
  """The three functions acados' ERK integrator calls, under the names and argument lists its generated
  model header declares; `p` is acados' parameter vector, unused (length 0 in the naive OCP).

  CasADi passes the sensitivity `Sx` as a dense 2x2 matrix; Scaly's CasADi layer refuses dense matrices
  (Scaly is row-major, CasADi column-major), so `Sx` and its derivative travel as flat column-major
  vectors, which acados copies the same way (`external_function_generic.c`, `d_cvt_colmaj_to_casadi`:
  a dense argument is `nrow * ncol` contiguous values).

  The network is written into each body, not called as a model `Function`: the derivative of a call
  node recomputes the callee's forward pass beside the call's own value, which costs 2x at 5 x 128
  (`todo.md`, CS-10)."""

  @sc.function(sc.L("x", NX), sc.L("u", NU), sc.L("p", n_p), name="wr_expl_ode_fun")
  def ode(x, u, p):
    return xdot(params, x, u)

  @sc.function(
    sc.L("x", NX),
    sc.L("Sx", NX * NX),
    sc.L("Sp", NX * NU),
    sc.L("u", NU),
    sc.L("p", n_p),
    output=sc.G("f", "Sx_dot", "Sp_dot"),
    name="wr_expl_vde_forw",
  )
  def vde_forw(x, Sx, Sp, u, p):
    f = xdot(params, x, u)
    jx, ju = sc.jacobian(f, x), sc.jacobian(f, u)
    sx = Sx.reshape((NX, NX)).T  # column-major in, so the row-major reshape is the transpose
    return f, (jx @ sx).T.reshape((NX * NX,)), jx @ Sp + ju.reshape((NX * NU,))

  @sc.function(sc.L("x", NX), sc.L("lam", NX), sc.L("u", NU), sc.L("p", n_p), name="wr_expl_vde_adj")
  def vde_adj(x, lam, u, p):
    f = xdot(params, x, u)
    return sc.concat([sc.jacobian(f, x).T @ lam, sc.jacobian(f, u).T @ lam])

  return {"wr_expl_ode_fun": ode, "wr_expl_vde_forw": vde_forw, "wr_expl_vde_adj": vde_adj}


def install_dropin(params, code_dir: Path, n_p: int = 0) -> list[Path]:
  """Replace acados' generated model sources in `code_dir/wr_model` by Scaly's. acados builds its C with
  `casadi_int` as `int`; the Scaly layer defaults it to CasADi's `long long` unless defined, so each
  file is prefixed with the definition."""
  written = []
  for name, fn in acados_functions(params, n_p).items():
    module = write_module(fn, code_dir / "wr_model" / "scaly", adapters=("casadi",))
    target = code_dir / "wr_model" / f"{name}.c"
    header = (code_dir / "wr_model" / "scaly" / module.header_name).read_text()
    source = (code_dir / "wr_model" / "scaly" / module.source_name).read_text().replace(f'#include "{module.header_name}"', header)
    target.write_text("#define casadi_int int\n" + source)
    written.append(target)
  return written


def taylor_function(params, nodes: int = N) -> sc.Function:
  """RTN-MPC's parameters at `nodes` points, one row each: `[a, f_D(a), vec(J_D(a))]`, the Jacobian
  flattened column-major, as ml-casadi's CasADi side reads it (`cs.reshape`)."""

  @sc.function(sc.L("x", NX), name="taylor_node")
  def node(a):
    y = mlp(params, a)
    return sc.concat([a, y, sc.jacobian(y, a).T.reshape((NX * NX,))])

  @sc.function(sc.L("xs", nodes * NX), name="taylor_params")
  def batch(xs):
    return sc.vmap(node, nodes, [(xs, 0, NX)])

  return batch
