"""The Real-time Neural MPC benchmark (Table II) with Scaly generating the network's code.

The model is the paper's: a double integrator `x = (s, s_dot)`, `u = s_ddot`, plus an MLP residual
`f_D(x)` read from the PyTorch state dict the baseline trains nothing into (`nn.load_torch_state_dict`, so
this file never imports torch). The layers stay dense matrix-vector loops in the generated C, and
their derivatives go through those loops.

Three uses of it, each against the matching baseline column of `baseline/run_acados.py`:

  dropin   acados with the exact network, its `expl_ode_fun`, `expl_vde_forw` and `expl_vde_adj`
           generated by Scaly instead of CasADi (`install_dropin`); HPIPM, condensing, ERK and the loop
           are acados' own, so this isolates the network's value and sensitivities
  taylor   the RTN-MPC loop with PyTorch's value-and-Jacobian replaced by one Scaly Function over the
           N shooting nodes (`taylor_params`)
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

import scaly as sc
from scaly import export, nn

NX, NU, N = 2, 1, 10


def layers(state_dict: dict[str, np.ndarray]) -> list[tuple[np.ndarray, np.ndarray | None]]:
  """`(W, b)` per linear layer, input first, in float64, from ml-casadi's MultiLayerPerceptron keys."""
  hidden = sorted({".".join(k.split(".")[:2]) for k in state_dict if k.startswith("hidden_layers.")}, key=lambda k: int(k.split(".")[1]))
  return nn.layers_from_state_dict(state_dict, ["input_layer", *hidden, "output_layer"])


def load(path: str | Path) -> list[tuple[np.ndarray, np.ndarray | None]]:
  return layers(nn.load_torch_state_dict(path))


def xdot(params, x: sc.Expr, u: sc.Expr) -> sc.Expr:
  """`[s_dot, u] + f_D(x)`, `f_D` the network: tanh on its hidden layers, linear out."""
  return sc.concat([x[1:2], u]) + nn.mlp(x, params)


def acados_functions(params, n_p: int = 0) -> dict[str, sc.Function]:
  """The three functions acados' ERK integrator calls, under the names and argument lists its generated
  model header declares (`scaly.export.acados_functions` for the model `wr`); `p` is acados' parameter
  vector, unused (length 0 in the naive OCP). The network is written into each body, not called as a
  model `Function`: the derivative of a call node recomputes the callee's forward pass beside the
  call's own value, which costs 2x at 5 x 128 (`todo.md`, CS-10)."""
  return export.acados_functions(lambda x, u, p: xdot(params, x, u), NX, NU, name="wr", n_p=n_p)


def install_dropin(params, code_dir: Path, n_p: int = 0) -> list[Path]:
  """Replace acados' generated model sources in `code_dir/wr_model` by Scaly's (`scaly.export.install_dropin`)."""
  return export.install_dropin(acados_functions(params, n_p), code_dir / "wr_model")


def taylor_function(params, nodes: int = N) -> sc.Function:
  """RTN-MPC's parameters at `nodes` points, one row each: `[a, f_D(a), vec(J_D(a))]`, the Jacobian
  flattened column-major, as ml-casadi's CasADi side reads it (`cs.reshape`)."""

  @sc.function(sc.L("x", NX), name="taylor_node")
  def node(a):
    y = nn.mlp(a, params)
    return sc.concat([a, y, sc.jacobian(y, a).T.reshape((NX * NX,))])

  @sc.function(sc.L("xs", nodes * NX), name="taylor_params")
  def batch(xs):
    return sc.vmap(node, nodes, [(xs, 0, NX)])

  return batch
