cmake_minimum_required(VERSION 3.15...3.30)
project(alloy_piqp LANGUAGES CXX)

find_package(Python 3.12 COMPONENTS Interpreter Development.Module Development.SABIModule REQUIRED)
execute_process(COMMAND "${Python_EXECUTABLE}" -m nanobind --cmake_dir OUTPUT_VARIABLE nanobind_DIR OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
find_package(nanobind CONFIG REQUIRED)

nanobind_add_module(_piqp_ext STABLE_ABI NB_STATIC piqp_ext.cpp)
target_compile_features(_piqp_ext PRIVATE cxx_std_17)
target_include_directories(_piqp_ext PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../src/alloy_piqp/include/piqp")
if(APPLE)
  target_link_libraries(_piqp_ext PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../src/alloy_piqp/lib/libpiqpc.dylib")
  set_target_properties(_piqp_ext PROPERTIES BUILD_RPATH "@loader_path/lib" INSTALL_RPATH "@loader_path/lib" BUILD_WITH_INSTALL_RPATH TRUE)
elseif(UNIX)
  target_link_libraries(_piqp_ext PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../src/alloy_piqp/lib/libpiqpc.so")
  set_target_properties(_piqp_ext PROPERTIES BUILD_RPATH "$ORIGIN/lib" INSTALL_RPATH "$ORIGIN/lib" BUILD_WITH_INSTALL_RPATH TRUE)
else()
  message(FATAL_ERROR "Windows is unsupported")
endif()
