[project]
name = "scaly-piqp"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["scaly"]
license = "BSD-2-Clause"
license-files = ["LICENSE.md"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.entry-points."scaly.solvers"]
piqp = "scaly_piqp:BACKEND"

[tool.hatch.build.targets.wheel]
packages = ["src/scaly_piqp"]
artifacts = [
  "src/scaly_piqp/_piqp_ext*.so",
  "src/scaly_piqp/_piqp_ext.pyi",
  "src/scaly_piqp/lib/*",
  "src/scaly_piqp/include/**/*",
  "src/scaly_piqp/licenses/**/*",
]

[tool.hatch.build.targets.sdist]
include = ["src/", "bindings/", "hatch_build.py", "licenses/"]

[tool.hatch.build.hooks.custom]
path = "hatch_build.py"

[tool.uv.sources]
scaly = { workspace = true }
