"""TinyMPC generated by Scaly as C specialized to one problem, with the library's own conventions.

``build_solver(problem)`` returns a Scaly ``Function``

    (state, x0, xref, uref, x_min, x_max, u_min, u_max) -> (state_next, iterations, solved, u0)

that performs one call of the TinyMPC library's ``tiny_solve``. The generated ADMM is
``scaly.ocp.tinyadmm.admm_solver``: the ADMM loop is a ``sc.while_loop``, and inside it the backward
pass for the affine terms and the forward rollout are two ``sc.scan``s over the horizon. The dynamics
and the Riccati cache (the library's infinite-horizon one, ``problem.cache``) are constants of the
generated code; the initial state, the references and the bounds are run-time inputs; the solver
state (trajectories, slacks, duals) goes in and comes back out, so that the caller warm-starts the
next solve the way the library keeps its workspace. ``state`` packs the fields of
``problem.STATE_FIELDS`` stage-major, exactly as ``pack_state`` does.

The linear cost of the references is the library's, ``Q + rho I`` times the reference, where the
OCP method ``sc.ocp.TinyADMM`` uses the problem's ``Q`` (see ``problem.py`` for the conventions this
reproduces). Bounds switched off in the settings are not inputs at all, and cones are generated only
for the sets the problem declares. Everything the library computes is computed in the same order,
so the generated solver and the library agree to rounding and take the same number of iterations.
"""

from __future__ import annotations

import numpy as np

import scaly as sc
from scaly.ir.types import Lowering
from scaly.ocp.tinyadmm import Layout, Shape, admm_solver

from problem import Cache, Problem, cache, zero_state


def _shape(p: Problem) -> Shape:
  return Shape(p.N, p.nx, p.nu, bool(p.state_cones), bool(p.input_cones))


def state_fields(p: Problem) -> tuple[str, ...]:
  """The state fields this problem carries: the cone duals only when it has cones."""
  return _shape(p).fields()


def state_layout(p: Problem) -> Layout:
  return _shape(p).state_layout()


def pack_state(p: Problem, state: dict[str, np.ndarray]) -> np.ndarray:
  return np.concatenate([np.asarray(state[f], dtype=float).reshape(-1) for f in state_fields(p)])


def unpack_state(p: Problem, flat: np.ndarray) -> dict[str, np.ndarray]:
  shape, lay = _shape(p), state_layout(p)
  out = {}
  for f in state_fields(p):
    a, b = lay[f]
    out[f] = np.asarray(flat[a:b]).reshape((p.N, p.nx) if shape.field_size(f) == p.N * p.nx else (p.N - 1, p.nu))
  return out


def build_solver(p: Problem, c: Cache | None = None, name: str = "tinympc_solve", lowering: Lowering = "auto", fixed_bounds=None) -> sc.Function:
  """The generated ``tiny_solve`` for ``p``; ``c`` overrides the cache (e.g. the library's own).

  ``fixed_bounds`` (a ``problem.Bounds``) makes the bounds constants of the generated code instead
  of inputs, as a code generator may when they never change; the loop then carries less."""
  c = cache(p) if c is None else c
  n = p.N

  def linear_cost(xref: sc.Expr, uref: sc.Expr) -> tuple[sc.Expr, sc.Expr, sc.Expr]:
    qref = -(xref * sc.const(np.tile(p.Q + p.rho, n)))
    rref = -(uref * sc.const(np.tile(p.R + p.rho, n - 1)))
    return qref, rref, -(sc.const(c.P.T) @ xref[(n - 1) * p.nx :])

  fixed = None if fixed_bounds is None else {k: getattr(fixed_bounds, k) for k in ("x_min", "x_max", "u_min", "u_max")}
  return admm_solver(
    p.A,
    p.B,
    c,
    knots=n,
    rho=p.rho,
    linear_cost=linear_cost,
    f=p.f,
    settings=p.settings,
    state_cones=p.state_cones,
    input_cones=p.input_cones,
    fixed_bounds=fixed,
    lowering=lowering,
    name=name,
  )


def bound_inputs(p: Problem, bounds, fixed: bool = False) -> list[np.ndarray]:
  """The bound inputs ``build_solver`` declares for ``p``, flattened stage-major."""
  out = []
  if fixed:
    return out
  if p.settings.en_state_bound:
    out += [bounds.x_min.reshape(-1), bounds.x_max.reshape(-1)]
  if p.settings.en_input_bound:
    out += [bounds.u_min.reshape(-1), bounds.u_max.reshape(-1)]
  return out


class Solver:
  """The generated solver called from Python (compiled on first call), keeping its warm-start
  state between calls as the library keeps its workspace."""

  def __init__(self, p: Problem, bounds, c: Cache | None = None, lowering: Lowering = "auto", fixed_bounds: bool = False) -> None:
    self.problem = p
    self.function = build_solver(p, c, lowering=lowering, fixed_bounds=bounds if fixed_bounds else None)
    self.state = pack_state(p, zero_state(p))
    self.bounds = bound_inputs(p, bounds, fixed_bounds)

  def __call__(self, x0: np.ndarray, xref: np.ndarray, uref: np.ndarray) -> tuple[np.ndarray, int, bool]:
    state, iterations, solved, u0 = self.function((self.state, np.asarray(x0, float), xref.reshape(-1), uref.reshape(-1), *self.bounds))
    self.state = state
    return u0, int(iterations), bool(solved)
