"""TinyMPC written once in Python and generated by Scaly as C specialized to one problem.

``build_solver(problem)`` returns a Scaly ``Function``

    (state, x0, xref, uref, x_min, x_max, u_min, u_max) -> (state_next, iterations, solved, u0)

that performs one call of the TinyMPC library's ``tiny_solve``: the ADMM loop is a
``sc.while_loop``, and inside it the backward pass for the affine terms and the forward rollout are
two ``sc.scan``s over the horizon. The dynamics and the Riccati cache are constants of the
generated code; the initial state, the references and the bounds are run-time inputs; the solver
state (trajectories, slacks, duals) goes in and comes back out, so that the caller warm-starts the
next solve the way the library keeps its workspace. ``state`` packs the fields of
``problem.STATE_FIELDS`` stage-major, exactly as ``pack_state`` does.

Bounds switched off in the settings are not inputs at all, and cones are generated only for the
sets the problem declares. Everything the library computes is computed in the same order, so the
generated solver and the library agree to rounding and take the same number of iterations (see
``problem.reference_solve`` for the conventions this reproduces).
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

import scaly as sc
from scaly.ir.types import Lowering

from problem import STATE_FIELDS, Cache, Cone, Problem, cache, zero_state


@dataclass(frozen=True)
class Layout:
  """Offsets of each field in the solver state and in the while-loop carry."""

  offsets: dict[str, tuple[int, int]]
  size: int

  def __getitem__(self, name: str) -> tuple[int, int]:
    return self.offsets[name]


def _field_size(p: Problem, name: str) -> int:
  return p.N * p.nx if name in ("x", "v", "vnew", "g", "gc", "vcnew", "qref", "x_min", "x_max") else (p.N - 1) * p.nu


def state_fields(p: Problem) -> tuple[str, ...]:
  """The state fields this problem carries: the cone duals only when it has cones."""
  return tuple(f for f in STATE_FIELDS if (f != "gc" or p.state_cones) and (f != "yc" or p.input_cones))


def state_layout(p: Problem) -> Layout:
  offsets, at = {}, 0
  for name in state_fields(p):
    offsets[name] = (at, at + _field_size(p, name))
    at += _field_size(p, name)
  return Layout(offsets, at)


def pack_state(p: Problem, state: dict[str, np.ndarray]) -> np.ndarray:
  return np.concatenate([np.asarray(state[f], dtype=float).reshape(-1) for f in state_fields(p)])


def unpack_state(p: Problem, flat: np.ndarray) -> dict[str, np.ndarray]:
  lay = state_layout(p)
  out = {}
  for f in state_fields(p):
    a, b = lay[f]
    out[f] = np.asarray(flat[a:b]).reshape((p.N, p.nx) if _field_size(p, f) == p.N * p.nx else (p.N - 1, p.nu))
  return out


def _carry_layout(p: Problem, runtime_bounds: bool = True) -> Layout:
  """The carry is the state, the per-solve slacks of the cones, the loop invariants (linear cost of
  the references, bounds) and the convergence flag. A loop body reads only its carry (todo C-112)."""
  names = list(state_fields(p))
  names += ["vcnew"] if p.state_cones else []
  names += ["zcnew"] if p.input_cones else []
  names += ["qref", "rref", "pnref"]
  names += ["x_min", "x_max"] if p.settings.en_state_bound and runtime_bounds else []
  names += ["u_min", "u_max"] if p.settings.en_input_bound and runtime_bounds else []
  offsets, at = {}, 0
  for name in names:
    size = p.nx if name == "pnref" else _field_size(p, name)
    offsets[name] = (at, at + size)
    at += size
  offsets["done"] = (at, at + 1)
  return Layout(offsets, at + 1)


def _project_cones(w: sc.Expr, rows: int, width: int, cones: tuple[Cone, ...]) -> sc.Expr:
  """``project_soc`` on every stage (row of ``w`` reshaped to ``(rows, width)``) for every cone."""
  m = w.reshape((rows, width))
  cols = [m[:, j] for j in range(width)]
  for c in cones:
    axis = cols[c.start + c.dim - 1]
    rest = cols[c.start : c.start + c.dim - 1]
    u0 = axis * c.mu
    a = sum((r * r for r in rest[1:]), rest[0] * rest[0]).sqrt()
    below, inside = sc.less_equal(a, -u0), sc.less_equal(a, u0)
    scale = 0.5 * (1.0 + u0 / a)

    def pick(value: sc.Expr, keep: sc.Expr) -> sc.Expr:
      return sc.where(below, 0.0, sc.where(inside, keep, value))

    for j, r in enumerate(rest):
      cols[c.start + j] = pick(scale * r, r)
    cols[c.start + c.dim - 1] = pick(scale * (a / c.mu), axis)
  return sc.stack(cols).T.reshape((rows * width,)) if len(cols) > 1 else cols[0]


def _backward_step(p: Problem, c: Cache, lowering: Lowering) -> sc.Function:
  """``d_i = Quu^-1 (B' p_{i+1} + r_i + BPf)``, ``p_i = q_i + (A - BK)' p_{i+1} - K' r_i + APf``."""
  pn, r, q = sc.sym("p", p.nx), sc.sym("r", p.nu), sc.sym("q", p.nx)
  d = sc.const(c.Quu_inv) @ (sc.const(p.B.T) @ pn + r + sc.const(c.BPf))
  p_prev = q + sc.const(c.AmBKt) @ pn - sc.const(c.Kinf.T) @ r + sc.const(c.APf)
  outs = [e.with_lowering(lowering) for e in (p_prev, d)]
  return sc.Function._from_exprs("tiny_backward_step", [pn, r, q], outs, ["p", "r", "q"], ["p_prev", "d"])


def _forward_step(p: Problem, c: Cache, lowering: Lowering) -> sc.Function:
  """``u_i = -K x_i - d_i``, ``x_{i+1} = A x_i + B u_i + f``."""
  x, d = sc.sym("x", p.nx), sc.sym("d", p.nu)
  u = -(sc.const(c.Kinf) @ x) - d
  x_next = sc.const(p.A) @ x + sc.const(p.B) @ u
  if p.f is not None:
    x_next = x_next + sc.const(p.fdyn)
  outs = [e.with_lowering(lowering) for e in (x_next, u, x_next)]
  return sc.Function._from_exprs("tiny_forward_step", [x, d], outs, ["x", "d"], ["x_next", "u", "x_out"])


def _iteration(p: Problem, c: Cache, lay: Layout, lowering: Lowering, fixed_bounds=None) -> tuple[sc.Function, sc.Function]:
  """One ADMM iteration of the library's ``solve`` (``update_linear_cost``, ``backward_pass_grad``,
  ``forward_pass``, ``update_slack``, ``update_dual``, ``termination_condition``) and the loop test."""
  n, nx, nu, rho, st = p.N, p.nx, p.nu, p.rho, p.settings
  carry = sc.sym("carry", lay.size)

  def get(name: str) -> sc.Expr:
    if fixed_bounds is not None and name in ("x_min", "x_max", "u_min", "u_max"):
      return sc.const(np.asarray(getattr(fixed_bounds, name), dtype=float).reshape(-1))
    a, b = lay[name]
    return carry[a:b]

  g, y = get("g"), get("y")
  # update_linear_cost
  q = get("qref") - rho * (get("vnew") - g)
  r = get("rref") - rho * (get("znew") - y)
  pn = get("pnref") - rho * (get("vnew")[(n - 1) * nx :] - g[(n - 1) * nx :])
  if p.state_cones:
    q = q - rho * (get("vcnew") - get("gc"))
    pn = pn - rho * (get("vcnew")[(n - 1) * nx :] - get("gc")[(n - 1) * nx :])
  if p.input_cones:
    r = r - rho * (get("zcnew") - get("yc"))
  # backward_pass_grad: i = N-2, ..., 0 reads r_i and q_i backwards; d comes out in that order
  _, d_rev = sc.scan(_backward_step(p, c, lowering), pn, [(r, (n - 2) * nu, -nu), (q, (n - 2) * nx, -nx)], length=n - 1)
  # forward_pass: i = 0, ..., N-2 reads d_i from the reversed stack
  x0 = get("x")[:nx]
  _, u, x_tail = sc.scan(_forward_step(p, c, lowering), x0, [(d_rev, (n - 2) * nu, -nu)], length=n - 1)
  x = sc.concat([x0, x_tail])
  # update_slack
  vnew, znew = x + g, u + y
  if st.en_state_bound:
    vnew = sc.minimum(get("x_max"), sc.maximum(get("x_min"), vnew))
  if st.en_input_bound:
    znew = sc.minimum(get("u_max"), sc.maximum(get("u_min"), znew))
  # update_dual
  new = {"x": x, "u": u, "vnew": vnew, "znew": znew, "g": g + x - vnew, "y": y + u - znew}
  if p.state_cones:
    vcnew = _project_cones(x + get("gc"), n, nx, p.state_cones)
    new["vcnew"], new["gc"] = vcnew, get("gc") + x - vcnew
  if p.input_cones:
    zcnew = _project_cones(u + get("yc"), n - 1, nu, p.input_cones)
    new["zcnew"], new["yc"] = zcnew, get("yc") + u - zcnew
  # termination_condition; v and z keep their values in the iteration that stops
  done = sc.logical_and(
    sc.logical_and(sc.less(sc.norm_inf(x - vnew), st.abs_pri_tol), sc.less(sc.norm_inf(u - znew), st.abs_pri_tol)),
    sc.logical_and(sc.less(sc.norm_inf(get("v") - vnew) * rho, st.abs_dua_tol), sc.less(sc.norm_inf(get("z") - znew) * rho, st.abs_dua_tol)),
  )
  new["v"] = sc.where(done, get("v"), vnew)
  new["z"] = sc.where(done, get("z"), znew)
  new["done"] = sc.cast(done, "float64").reshape((1,))
  parts = [new.get(name, get(name)) for name in lay.offsets]
  body = sc.Function._from_exprs("tiny_admm_iteration", [carry], [sc.concat(parts)], ["carry"], ["next"])
  cond = sc.Function._from_exprs("tiny_not_converged", [carry], [sc.less(get("done")[0], 0.5)], ["carry"], ["go_on"])
  return body, cond


def build_solver(p: Problem, c: Cache | None = None, name: str = "tinympc_solve", lowering: Lowering = "auto", fixed_bounds=None) -> sc.Function:
  """The generated ``tiny_solve`` for ``p``; ``c`` overrides the cache (e.g. the library's own).

  ``fixed_bounds`` (a ``problem.Bounds``) makes the bounds constants of the generated code instead
  of inputs, as a code generator may when they never change; the loop then carries less.

  ``lowering`` is the Scaly lowering of the two stage steps: ``"auto"`` expands small ones into
  straight-line code with the matrices as literals (zeros skipped), ``"block"`` keeps them as
  loops over constant tables, ``"scalar"`` forces the expansion."""
  c = cache(p) if c is None else c
  if p.N < 2:
    raise ValueError("TinyMPC needs a horizon of at least two knot points")
  for cones, width in ((p.state_cones, p.nx), (p.input_cones, p.nu)):
    for cone in cones:
      if cone.dim < 2 or cone.start < 0 or cone.start + cone.dim > width:
        raise ValueError(f"cone {cone} does not fit a vector of {width}")
  n, nx, nu, st = p.N, p.nx, p.nu, p.settings
  slay, clay = state_layout(p), _carry_layout(p, fixed_bounds is None)
  body, cond = _iteration(p, c, clay, lowering, fixed_bounds)

  state, x0 = sc.sym("state", slay.size), sc.sym("x0", nx)
  xref, uref = sc.sym("xref", n * nx), sc.sym("uref", (n - 1) * nu)
  inputs, names = [state, x0, xref, uref], ["state", "x0", "xref", "uref"]
  bounds = {}
  if st.en_state_bound and fixed_bounds is None:
    bounds["x_min"], bounds["x_max"] = sc.sym("x_min", n * nx), sc.sym("x_max", n * nx)
  if st.en_input_bound and fixed_bounds is None:
    bounds["u_min"], bounds["u_max"] = sc.sym("u_min", (n - 1) * nu), sc.sym("u_max", (n - 1) * nu)
  inputs += list(bounds.values())
  names += list(bounds)

  def field(name: str) -> sc.Expr:
    a, b = slay[name]
    return state[a:b]

  x = sc.concat([x0, field("x")[nx:]])  # tiny_set_x0
  init = {f: field(f) for f in slay.offsets}
  init["x"] = x
  if p.state_cones:
    init["vcnew"] = x
  if p.input_cones:
    init["zcnew"] = field("u")
  init["qref"] = -(xref * sc.const(np.tile(p.Q + p.rho, n)))
  init["rref"] = -(uref * sc.const(np.tile(p.R + p.rho, n - 1)))
  init["pnref"] = -(sc.const(c.Pinf.T) @ xref[(n - 1) * nx :])
  init.update(bounds)
  init["done"] = sc.const(np.zeros(1))
  final, iterations = sc.while_loop(cond, body, sc.concat([init[k] for k in clay.offsets]), max_iter=st.max_iter)
  out_state = sc.concat([final[clay[f][0] : clay[f][1]] for f in slay.offsets])
  solved = sc.greater(final[clay["done"][0]], 0.5)
  u0 = final[clay["u"][0] : clay["u"][0] + nu]
  # The output is not called ``state``: an output named like an input is read back from the output
  # buffer by the generated code (todo C-124), so the names stay distinct.
  return sc.Function._from_exprs(name, inputs, [out_state, iterations, solved, u0], names, ["state_next", "iterations", "solved", "u0"])


def bound_inputs(p: Problem, bounds, fixed: bool = False) -> list[np.ndarray]:
  """The bound inputs ``build_solver`` declares for ``p``, flattened stage-major."""
  out = []
  if fixed:
    return out
  if p.settings.en_state_bound:
    out += [bounds.x_min.reshape(-1), bounds.x_max.reshape(-1)]
  if p.settings.en_input_bound:
    out += [bounds.u_min.reshape(-1), bounds.u_max.reshape(-1)]
  return out


class Solver:
  """The generated solver called from Python (compiled on first call), keeping its warm-start
  state between calls as the library keeps its workspace."""

  def __init__(self, p: Problem, bounds, c: Cache | None = None, lowering: Lowering = "auto", fixed_bounds: bool = False) -> None:
    self.problem = p
    self.function = build_solver(p, c, lowering=lowering, fixed_bounds=bounds if fixed_bounds else None)
    self.state = pack_state(p, zero_state(p))
    self.bounds = bound_inputs(p, bounds, fixed_bounds)

  def __call__(self, x0: np.ndarray, xref: np.ndarray, uref: np.ndarray) -> tuple[np.ndarray, int, bool]:
    state, iterations, solved, u0 = self.function((self.state, np.asarray(x0, float), xref.reshape(-1), uref.reshape(-1), *self.bounds))
    self.state = state
    return u0, int(iterations), bool(solved)
