"""The Scaly side of the embedded-QP study: the generated PIQP and the PIQP library, one horizon per process.

    uv run examples/case_studies/embedded_qp/run_scaly.py --horizon 20 --solver scaly_sparse --out results/scaly_T20_scaly_sparse.json

Solvers: `scaly_sparse` is PIQP's algorithm generated by `scaly.solvers.ipm` for this problem's KKT
pattern (`examples/qp_solvers/generated_piqp.py`, which becomes `backend="scaly"` in Tier 4);
`piqp_sparse` is the vendored PIQP 0.6.2 library behind `sc.opt.solver(problem, "piqp", sparse=True)`.
Both at `eps_abs = eps_rel = 1e-7`, the benchmark's tolerance. Timing is `examples/qp_solvers`'
harness: the generated entry point called from C (`time_entry.c`) on the instance's parameters, which
include the data the QOCO timer rewrites (`Q`, `R`, `x0`); the minimum over `--repeats` calls.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
import time
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent.parent / "qp_solvers"))
TOL = 1e-7


def build(problem, solver: str):
  import scaly as sc
  from scaly.solvers.ipm import Settings

  import generated_piqp

  name = f"{problem.name}_{solver}"
  if solver == "scaly_sparse":
    return generated_piqp.solver(problem, "sparse", Settings(eps_abs=TOL, eps_rel=TOL), name=name)
  return sc.opt.solver(problem, sc.opt.PIQP(sparse=True, options={"eps_abs": TOL, "eps_rel": TOL}), name=name)


def main() -> None:
  from scaly.opt import solver_stats

  ap = argparse.ArgumentParser()
  ap.add_argument("--horizon", type=int, required=True)
  ap.add_argument("--solver", choices=("scaly_sparse", "piqp_sparse"), required=True)
  ap.add_argument("--instances", type=int, default=5)
  ap.add_argument("--repeats", type=int, default=200)
  ap.add_argument("--out", type=Path, required=True)
  args = ap.parse_args()
  work = Path(tempfile.mkdtemp(prefix="embedded-qp-"))
  os.environ.setdefault("SCALY_CACHE_DIR", str(work / "cache"))
  from scaly.codegen import render_c_module
  from scaly.codegen.abi import c_ident
  from scaly.codegen.jit import compile_flags

  import compare as qp  # examples/qp_solvers/compare.py: sh, object_size, time_driver
  from problem import HORIZONS, instances, objective, problem

  t0 = time.perf_counter()
  p = problem(args.horizon)
  fun = build(p, args.solver)
  t_build = time.perf_counter() - t0
  t0 = time.perf_counter()
  module = render_c_module(fun)
  t_generate = time.perf_counter() - t0
  src, lib = work / f"{c_ident(fun.name)}.c", work / f"lib{c_ident(fun.name)}.so"
  src.write_text(module.body)
  t0 = time.perf_counter()
  qp.sh([os.environ.get("SCALY_CC", "cc"), *compile_flags(), "-fPIC", "-shared", str(src), *module.link_flags, "-lm", "-o", str(lib)])
  t_compile = time.perf_counter() - t0
  row = {
    "horizon": args.horizon,
    "solver": args.solver,
    "t_build": t_build,
    "t_generate": t_generate,
    "t_compile": t_compile,
    "c_bytes": len(module.body.encode()),
    "object_bytes": qp.object_size(lib),
    "text_bytes": text_bytes(lib),
    "instances": [],
  }
  every = instances(sorted(set(HORIZONS) | {args.horizon}), args.instances)
  zeros = p.vars.unflatten(tuple(np.zeros(s) for s in p.vars.shapes))
  for i in range(args.instances):
    d = every[(args.horizon, i)]
    params = (d["q"], d["r"], d["x0"])
    if args.solver == "scaly_sparse":
      out = fun(params)
      x = np.asarray(out[0])
      u, xs = x[: args.horizon * 4].reshape(args.horizon, 4), x[args.horizon * 4 :].reshape(args.horizon + 1, 8)
      status, iters = int(out[4]), int(out[5])
      flat = [np.asarray(a, float) for a in p.params.flatten_numerical(params, "parameters")]
    else:
      args_ = (zeros, zeros, np.zeros(p.n_eq), np.zeros(p.n_ineq), params)
      (u, xs), *_ = fun(*args_)
      st = solver_stats(fun)
      status, iters = (1 if st.to_solver_status().name == "OK" else 0), int(st.iter)
      flat = [np.asarray(a, float) for a in fun.input_tree.flatten_numerical(args_, "solver inputs")]
    sizes_out = [int(e.size) for e in fun.outputs]
    blob = np.array([len(flat), len(sizes_out), module.workspace_size, *[a.size for a in flat], *sizes_out], dtype="<i8").tobytes()
    blob += b"".join(np.ascontiguousarray(a, dtype="<f8").tobytes() for a in flat)
    (work / "inputs.bin").write_bytes(blob)
    best, median = qp.sh(
      [str(qp.time_driver()), str(lib), c_ident(fun.name), str(work / "inputs.bin"), str(args.repeats), str(work / "outputs.bin")]
    ).split()
    row["instances"].append(
      {
        "instance": i,
        "status": "solved" if status == 1 else f"status {status}",
        "iterations": iters,
        "obj": objective(args.horizon, d, np.asarray(u), np.asarray(xs)),
        "solve_s": float(best) * 1e-9,
        "solve_median_s": float(median) * 1e-9,
      }
    )
  args.out.parent.mkdir(parents=True, exist_ok=True)
  args.out.write_text(json.dumps(row, indent=1))


def text_bytes(path: Path) -> int:
  import subprocess

  out = subprocess.run(["size", "-m", str(path)] if sys.platform == "darwin" else ["size", "-A", str(path)], capture_output=True, text=True).stdout
  for line in out.splitlines():
    parts = line.replace(":", " ").split()
    for tag in ("__text", ".text"):
      if tag in parts:
        return int(next(q for q in parts[parts.index(tag) + 1 :] if q.isdigit()))
  return 0


if __name__ == "__main__":
  main()
