"""The curated public surface: re-exports only, no definitions of its own (``docs/dev/codebase.md``)."""

from typing import Any

from .codegen.abi import C_API_SIGNATURE, BufferType, c_api_signature
from .ad import jvp, jvp_many, vjp, vjp_many
from .function.sugar import custom_derivative, scan, vmap, while_loop
from .function.api import (
  adjoint,
  forward,
  function,
  gradient,
  hessian,
  jacobian,
  lagrangian_hessian,
  sparse_hessian,
  sparse_jacobian,
  sparse_lagrangian_hessian,
)
from .ir.text import render_expr_assembly, render_program_assembly
from .ir.expr import (
  COMMON_OPS,
  Expr,
  ExprOp,
  OP_INFO,
  atan2,
  cast,
  concat,
  copysign,
  dot,
  equal,
  format_expr,
  gather,
  greater,
  greater_equal,
  index_add,
  index_set,
  isfinite,
  less,
  less_equal,
  logical_and,
  logical_not,
  logical_or,
  maximum,
  minimum,
  norm_1,
  norm_2,
  norm_inf,
  not_equal,
  put,
  put_add,
  reduce_max,
  reduce_min,
  scatter,
  segment_max,
  segment_min,
  segment_sum,
  split,
  stack,
  sumsqr,
  take,
  vec,
  where,
)
from .function import ConcreteFunction, Function, G, L, NotConcrete, factory
from .linalg import S, SparseMatrix
from . import integrators as integrators
from . import interp as interp
from . import mpc as mpc
from .utils.options import Options, get_options, options, set_options
from .ir.match import Pattern, PatternMatcher, rewrite
from .passes.expr import cse, cse_many, simplify
from .solvers import (
  SCALY_SOLVER_STATS_VERSION,
  ScalySolveStatus,
  Bounded,
  NO_LB,
  NO_UB,
  NotQuadratic,
  Problem,
  ProblemSpec,
  QPData,
  SolverStats,
  SolverStatus,
  bounded,
  problem,
  qp_problem,
  solver,
  solver_stats,
)
from .ir.expr_spec import spec_expr, spec_expr_shared, verify_expr
from .ir.spec import Rule, Spec, VerifyError
from .ad.sparse import SparseJacobian, sparse_jacobian_colored, sparse_jacobian_reference
from .ad.sparsity import color_groups, column_coloring, jacobian_sparsity, star_coloring
from .ir.types import BACKEND_SUPPORT, BackendSupport, DeviceSpec, DType, ScalarType, SparsityType, TensorType, as_dtype, backend_supports, dtypes

sym = Expr.sym
const = Expr.const


def __getattr__(name: str) -> Any:
  # Graph JSON is viz, and reaching it runs ``scaly/viz/__init__.py``, which pulls in the whole
  # backend and arms the render observer. Deferring that to the first use of these two names
  # keeps a plain ``import scaly`` free of it.
  if name in ("expr_graph", "program_graph"):
    from .viz import graph

    return getattr(graph, name)
  raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
  "BACKEND_SUPPORT",
  "SCALY_SOLVER_STATS_VERSION",
  "ScalySolveStatus",
  "BackendSupport",
  "Bounded",
  "BufferType",
  "C_API_SIGNATURE",
  "COMMON_OPS",
  "DType",
  "DeviceSpec",
  "OP_INFO",
  "Expr",
  "ConcreteFunction",
  "Function",
  "G",
  "L",
  "NO_LB",
  "NO_UB",
  "NotConcrete",
  "NotQuadratic",
  "ExprOp",
  "Pattern",
  "PatternMatcher",
  "ScalarType",
  "Problem",
  "ProblemSpec",
  "QPData",
  "SolverStats",
  "SolverStatus",
  "S",
  "Spec",
  "SparseJacobian",
  "SparseMatrix",
  "SparsityType",
  "TensorType",
  "VerifyError",
  "Rule",
  "adjoint",
  "as_dtype",
  "atan2",
  "backend_supports",
  "bounded",
  "c_api_signature",
  "dtypes",
  "color_groups",
  "column_coloring",
  "star_coloring",
  "concat",
  "const",
  "cse",
  "cse_many",
  "dot",
  "expr_graph",
  "format_expr",
  "forward",
  "factory",
  "function",
  "gather",
  "gradient",
  "hessian",
  "jacobian",
  "jacobian_sparsity",
  "jvp",
  "jvp_many",
  "vjp",
  "vjp_many",
  "lagrangian_hessian",
  "vmap",
  "scan",
  "while_loop",
  "custom_derivative",
  "maximum",
  "minimum",
  "cast",
  "copysign",
  "equal",
  "greater",
  "greater_equal",
  "index_add",
  "index_set",
  "isfinite",
  "less",
  "less_equal",
  "logical_and",
  "logical_not",
  "logical_or",
  "not_equal",
  "put",
  "put_add",
  "where",
  "problem",
  "qp_problem",
  "norm_1",
  "norm_2",
  "norm_inf",
  "reduce_max",
  "reduce_min",
  "Options",
  "get_options",
  "options",
  "set_options",
  "program_graph",
  "solver",
  "solver_stats",
  "render_expr_assembly",
  "render_program_assembly",
  "rewrite",
  "scatter",
  "segment_max",
  "segment_min",
  "segment_sum",
  "sparse_hessian",
  "sparse_lagrangian_hessian",
  "simplify",
  "sparse_jacobian",
  "sparse_jacobian_colored",
  "sparse_jacobian_reference",
  "spec_expr",
  "spec_expr_shared",
  "split",
  "stack",
  "sumsqr",
  "take",
  "vec",
  "sym",
  "verify_expr",
]
