"""The curated public surface: re-exports only, no definitions of its own (``docs/dev/codebase.md``)."""

from .codegen.abi import C_API_SIGNATURE, c_api_signature
from .ad import jvp, jvp_many, vjp
from .function.sugar import vmap, broadcast, window
from .function.api import (
  adjoint,
  forward,
  function,
  gradient,
  hessian,
  jacobian,
  lagrangian_hessian,
  sparse_hessian,
  sparse_jacobian,
  sparse_lagrangian_hessian,
)
from .ir.text import render_expr_assembly, render_program_assembly
from .ir.expr import (
  COMMON_OPS,
  Expr,
  ExprOp,
  OP_INFO,
  atan2,
  concat,
  dot,
  format_expr,
  gather,
  maximum,
  minimum,
  norm_2,
  scatter,
  segment_sum,
  split,
  stack,
  sumsqr,
  vec,
)
from .function import Function, group, arg, factory
from .ir.match import Pattern, PatternMatcher, rewrite
from .passes.expr import cse, cse_many, simplify
from .solvers import (
  SCALY_SOLVER_STATS_VERSION,
  ScalySolveStatus,
  Bounded,
  NO_LB,
  NO_UB,
  NotQuadratic,
  Problem,
  ProblemSpec,
  QPData,
  Solver,
  SolverLibraryError,
  SolverStats,
  SolverStatus,
  bounded,
  problem,
  qp_problem,
  solver,
)
from .ir.expr_spec import spec_expr, spec_expr_shared, verify_expr
from .ir.spec import Rule, Spec, VerifyError
from .ad.sparse import SparseJacobian, sparse_jacobian_colored, sparse_jacobian_reference
from .ad.sparsity import color_groups, column_coloring, jacobian_sparsity, star_coloring
from .ir.types import DeviceSpec, DType, SparsityPattern, TensorType, as_dtype, dtypes

sym = Expr.sym
const = Expr.const


__all__ = [
  "SCALY_SOLVER_STATS_VERSION",
  "ScalySolveStatus",
  "Bounded",
  "C_API_SIGNATURE",
  "COMMON_OPS",
  "DType",
  "DeviceSpec",
  "OP_INFO",
  "Expr",
  "Function",
  "group",
  "arg",
  "NO_LB",
  "NO_UB",
  "NotQuadratic",
  "ExprOp",
  "Pattern",
  "PatternMatcher",
  "Problem",
  "ProblemSpec",
  "QPData",
  "Solver",
  "SolverLibraryError",
  "SolverStats",
  "SolverStatus",
  "Spec",
  "SparseJacobian",
  "SparsityPattern",
  "TensorType",
  "VerifyError",
  "Rule",
  "adjoint",
  "as_dtype",
  "atan2",
  "bounded",
  "c_api_signature",
  "dtypes",
  "color_groups",
  "column_coloring",
  "star_coloring",
  "concat",
  "const",
  "cse",
  "cse_many",
  "dot",
  "format_expr",
  "forward",
  "factory",
  "function",
  "gather",
  "gradient",
  "hessian",
  "jacobian",
  "jacobian_sparsity",
  "jvp",
  "jvp_many",
  "vjp",
  "lagrangian_hessian",
  "vmap",
  "broadcast",
  "window",
  "maximum",
  "minimum",
  "problem",
  "qp_problem",
  "norm_2",
  "solver",
  "render_expr_assembly",
  "render_program_assembly",
  "rewrite",
  "scatter",
  "segment_sum",
  "sparse_hessian",
  "sparse_lagrangian_hessian",
  "simplify",
  "sparse_jacobian",
  "sparse_jacobian_colored",
  "sparse_jacobian_reference",
  "spec_expr",
  "spec_expr_shared",
  "split",
  "stack",
  "sumsqr",
  "vec",
  "sym",
  "verify_expr",
]
